//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18408
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace AssemblyCSharp
{
		public class StatusBar
		{
		public void ShowBar(bool enable,int gold,int level,int points)
		{
						if (enable) {
								GUI.Box (new Rect (0, 0, 1366, 20), "");
								GUI.Label (new Rect (3, 0, 50, 20), "Level:" + level.ToString ());
								GUI.Label (new Rect (75, 0, 200, 20), "Points:" + points.ToString ());
								GUI.Label (new Rect (265, 0, 100, 20), "Gold:" + gold.ToString ());

								if (GUI.Button (new Rect (1150, 0, 50, 20), "Меню")) {


								}
						}
				}
				public StatusBar ()
				{

				}
	}
}

